name: Koyeb Redeployment

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install and Configure Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Verify Koyeb CLI Installation
        run: koyeb --version

      - name: Check CLI Path
        run: which koyeb

      - name: List Koyeb Services
        run: koyeb service list

      - name: Deploy to Koyeb
        run: |
          koyeb service redeploy hilarious-mirabelle/mybotwork
