name: Koyeb Redeployment

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://get.koyeb.com/install.sh | bash
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH
          export PATH="$HOME/.koyeb/bin:$PATH"

      - name: Verify Koyeb CLI Installation
        run: koyeb --version

      - name: Deploy to Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          koyeb service redeploy hilarious-mirabelle/mybotwork
