name: Koyeb Redeployment

on:
  schedule:
    - cron: '*/15 * * * *'  
  workflow_dispatch:  

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install and Configure Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Verify Koyeb CLI Installation
        run: koyeb version

      - name: Deploy to Koyeb with Skip Build
        continue-on-error: true  # Prevents workflow failure on redeploy errors
        run: |
          koyeb service redeploy universal-paige/mybotwork --skip-build || echo "Redeployment skipped, possibly due to rate limit. Will retry in next run."
       
