name: Koyeb Redeployment

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install and Configure Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Verify Koyeb CLI Installation
        run: koyeb version

      - name: Deploy to Koyeb with Skip Build
        run: |
          koyeb service redeploy hilarious-mirabelle/mybotwork --skip-build
